### ISSUE TITLE
What is the relationship between kill_query_timeout and read_timeout？

### ISSUE THREAD

**Issue by byzhaozihan** [mailru/go-clickhouse#146]
What is the relationship between kill_query_timeout and read_timeout, for example, I want to terminate the query and return empty data every time the query time exceeds 10s, which parameter needs to be set

**Comment by Slach** [comment]
`read_timeout` it's a TCP socket level parameter, timeout for reading response data from TCP socket.

`kill_query_timeout` works only together with `kill_query`, and mean timeout for reading response after KILL QUERY statement sent
`kill_query`  means send KILL QUERY statement if we have transport error (read_timeout for example)
look details 
https://github.com/mailru/go-clickhouse/blob/50ee627febba154af1dd7cdd6f597321bc520934/conn.go#L191-L220

I worry you can't achieve your goals with client library in any language
root cause, according to documentation https://clickhouse.com/docs/en/sql-reference/statements/kill/#kill-query-statement
`KILL QUERY` statement work in asynchronous mode or even never work until query end in the natural way

Cause, even you call `KILL QUERY ... SYNC` it means just setup `kill flag` for selected running queries, and query processor will check this flag, but query processor do it not so often as you expect and will wait when current part of executed query will end

So, you can be sure `KILL QUERY` works, but real query killing happens somewhat later than you expect.

**Comment by byzhaozihan** [comment]
> 

@Slach 
So if I only set read_timeout = 5 seconds, but the actual query takes 10 seconds, what will happen after 5 seconds

**Comment by Slach** [comment]
According to https://github.com/mailru/go-clickhouse/blob/50ee627febba154af1dd7cdd6f597321bc520934/conn.go#L71-L81

If you set `read_timeout = 5` and send query, if clickhouse-server will not send any HTTP headers inside 5 sec, then TCP connection should RESET from client side

If you set `kill_query=1` `mailru/clickhouse-go` will send another HTTP request `KILL QUERY WHERE query_id=...`
If not, you will just receive timeout error from `mailru/clickhouse-go`

From `clickhouse-server` perspective, it will look like error with something `client abnormal close connection` when he will try to send data into client HTTP connection socket.
And maybe `KILL QUERY WHERE query_id=...` will do nothing. It depends on how heavy load will in your query.

But you should check it in `grep <your_query_id> /var/log/clickhouse-server/clickhouse-server.log`

**Comment by byzhaozihan** [comment]
@Slach 
I get it, thanks a lot
